# Generated by Django 3.1.4 on 2020-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(default='/posyandu3.png', upload_to='documents/')),
                ('isi', models.TextField()),
                ('upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
