# Generated by Django 3.1.4 on 2020-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='thumbnail',
            field=models.ImageField(default='/posyandu3.jpg', upload_to='documents/'),
        ),
    ]
