# Generated by Django 3.1.4 on 2020-12-09 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ibu', models.CharField(max_length=100)),
                ('tgl_lahir_ibu', models.DateTimeField()),
                ('gol_darah_ibu', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], default='A', max_length=2)),
                ('telpon', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=100)),
                ('nama_anak', models.CharField(max_length=100)),
                ('tgl_lahir_anak', models.DateTimeField()),
                ('gol_darah_anak', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], default='A', max_length=2)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
