# Generated by Django 3.1.4 on 2020-12-09 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_perkembangananak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perkembangananak',
            name='bulan',
        ),
        migrations.AddField(
            model_name='perkembangananak',
            name='tgl_lahir_anak',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
