# Generated by Django 3.1.4 on 2020-12-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201210_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perkembangananak',
            old_name='tgl_lahir_anak',
            new_name='tanggal',
        ),
    ]
